INSERT INTO departments (name)
VALUES  ('Accounting'),
        ('Sales'),
        ('Logistics'),
        ('Retail'),
        ('Acquisitions'),
        ('Human Resources'),
        ('I.T.');

INSERT INTO roles (title, salary, department_id)
VALUES  ('Accountant', 50, 1),
        ('CPA', 100, 1),
        ('Singles Salesman', 24, 2),
        ('Wholesaler', 26, 2),
        ('Travel Coordinator', 40, 3),
        ('Shipper', 41, 3),
        ('Packager', 42, 3),
        ('Shipping Manager', 60, 3),
        ('Front Desk', 31, 4),
        ('Front Floor', 32, 4),
        ('Singles Buyer', 44, 5),
        ('Wholesale Buyer', 46, 5),
        ('HR Lady', 49, 6),
        ('Database Handler', 50, 7),
        ('IT Technician', 61, 7),
        ('Backend Developer', 62, 7);

INSERT INTO employees (first_name, last_name, role_id, manager_id)
VALUES  ('Angela', 'Chance', 2, NULL),
        ('Lance', 'Dragon', 8, NULL),
        ('Adam', 'Anderson', 1, 1),
        ('Amy', 'Alexander', 1, 1),
        ('Sally', 'Sellers', 3, NULL),
        ('Samuel', 'Sellington', 3, NULL),
        ('Stanley', 'Worthington', 4, NULL),
        ('Samantha', 'Whales', 4, NULL),
        ('Larry', 'Thomas', 5, NULL),
        ('Luke', 'Shipperson', 6, 2),
        ('Langdon', 'Samson', 6, 2),
        ('Linda', 'Paulson', 7, 2),
        ('Laura', 'Pickler', 7, 2),
        ('Rachel', 'Fredida', 9, NULL),
        ('Rihanna', 'Franklin', 9, NULL),
        ('Robert', 'Flood', 10, NULL),
        ('Raymond', 'Franklin', 10, NULL),
        ('Quinn', 'Singleton', 11, NULL),
        ('Quincey', 'Wells', 12, NULL),
        ('Hannah', 'Hanson', 13, NULL),
        ('Isaac', 'Isaacson', 14, NULL),
        ('Idra', 'Iverson', 15, NULL),
        ('Isabelle', 'Inkler', 15, NULL),
        ('Isaiah', 'Baxter', 16, NULL);